---
repos:
  # Set the list of basic git hooks to find and fix common problems in the current working tree.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9
    hooks:
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
