name: detach build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step -- 1.
        uses: actions/checkout@v3

      - name: Step -- 2.
        run: gcc -Wall -Wextra -Werror -Wno-unused-parameter detach.c -o detach
